### ISSUE TITLE
Redeployment with a launcher extending io.vertx.core.Launcher

### ISSUE THREAD

**Issue by cescoffier** [fabric8io/vertx-maven-plugin#103]
So far, it does not work...

When using a launcher class extending `Launcher`, we forward the args to the `Launcher`.  However, as it's not the Vert.x Launcher we don't build the command line.

**Comment by kameshsampath** [comment]
@cescoffier - not able to understand, you mean to say the `new Launcher().dispatch(args)` kind of thing will not pass the args ?

**Comment by cescoffier** [comment]
When someone uses a launcher extending the `io.vertx.core.Launcher`, it expects the regular `Launcher` parameter (`run verticle....`). Right now, we don't pass any parameter, and we fail with an obscure error (ClassNotFound redeploy-termination-period=1000).

**Comment by cescoffier** [comment]
To reproduce it, just create a project with a custom launcher extending `io.vertx.core.Launcher` with the following main:

```
public class MyLauncher extends Launcher {
  public static void main String[]) {
      new MyLauncher().dispatch(args);
  }
}
```

With this launcher we neither, run / start nor manage the redeployment.

**Comment by kameshsampath** [comment]
got it thanks, let me check and fix it up

**Comment by cescoffier** [comment]
CC @ctranxuan
