### ISSUE TITLE
Support for adding system properties

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/vertx-maven-plugin#104]
the plugin should allow support for passing system properties to the vert.x application launched/run. Similar to how other maven plugin. 

e.g.

```
 <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>vertx-maven-plugin</artifactId>
                <version>${fabric8-vertx-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>vmp</id>
                        <goals>
                            <goal>initialize</goal>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <redeploy>true</redeploy>
                    <systemProperties>
                       <prop.a>Hello</prop.a>
                   </systemProperties>
                </configuration>
            </plugin>
```
@cescoffier - thoughts ?

**Comment by cescoffier** [comment]
Cannot this be done with: `-Dvertx.runArgs="-Dprop.a=hello"` ?

**Comment by pn-santos** [comment]
I came across this recently and at least for configuring `vertx.logger-delegate-factory-class-name` it doesn't work. Tried doing `-Dvertx.runArgs="-Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory"` but I still see the `INFO: Succeeded in deploying verticle` message (meaning it doesn't pickup the log4j2 config).

If I run the jar manually with `java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar target/vertx-service.jar` then it works and vertx logs go through log4j2

Also tried passing them as jvmArgs and that also doesn't work

**Comment by cescoffier** [comment]
Can be done using:

```
<jvmArgs>
-Da=Hello
</jvmArgs>
