### ISSUE TITLE
Adding destFileName to vertx-web-client.js file

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/vertx-maven-plugin#113]
traditionally the vertx-web-client.js are being called `vertx-eventbus.js`, hence will it be nice to add option to allow the destfile name for web client javascript files via plugin ? 

some thing like 
```
<webrootDestFiles>
    <vertx-web-client>vertx-eventbus</vertx-web-client>
    <jquery>my-jquery</jquery>
</webrootDestFiles>
```
so when the initialize goal executes - it will copy `vertx-web-client --> vertx-eventbus` and `jquery --> my-jquery` with extensions as is

@cescoffier  - thoughts ?

**Comment by cescoffier** [comment]
For js dependencies, yes, it can be an interesting feature. For webjars, it's more tricky.
It's probably something we should to in combination of #71 - a way to configure the content of the fat jar.

**Comment by cescoffier** [comment]
This is not required anymore. The plugin has now an `archive` attribute that can include specific files where the output directory and destination name can be configured.

Reference: https://github.com/reactiverse/vertx-maven-plugin/issues/6
