### ISSUE TITLE
startMode "exploded" does not generate exploded folder in target-directory

### ISSUE THREAD

**Issue by nimo23** [fabric8io/vertx-maven-plugin#119]
When using "vertx:start" with "startMode: exploded", then I expect, that the "exploded archive" is used instead of a "jar" when running the application. However, I cannot find the "exploded archive" within my "target"-directory. Where is it?

**Comment by cescoffier** [comment]
It uses the "target/classes" directory and the Maven dependencies. It does not generate the exploded archive. Actually, it's an interesting use case. Can you tell us more about it?

**Comment by nimo23** [comment]
Would be nice to use "exploded archive" instead of "target/classes" so all the files within the can be hot changed (by other editors/browsersync/etc). 

http://stackoverflow.com/questions/3906881/advantages-disadvantages-to-exploded-wars.

**Comment by nimo23** [comment]
However, I dont know, if there is a general need for that..?
