### ISSUE TITLE
Plugin execution not covered by lifecycle configuration: initialize

### ISSUE THREAD

**Issue by nimo23** [fabric8io/vertx-maven-plugin#120]
I am using this:

```
<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>vertx-maven-plugin</artifactId>
				<version>1.0.7</version>
				<executions>
					<execution>
						<id>vmp</id>
						<goals>
							<goal>initialize</goal>
							<goal>package</goal>
						</goals>
					</execution>
				</executions>
....
```

and maven prints the following warning/error:

"Plugin execution not covered by lifecycle configuration: io.fabric8:vertx-maven-plugin:1.0.7:initialize (execution: vmp, phase: initialize)"

So should I delete goal "initialize" ?

**Comment by cescoffier** [comment]
Are you executing it in Eclipse ?

**Comment by nimo23** [comment]
Yes, I use eclipse.

**Comment by cescoffier** [comment]
Ah ah, so you just hit the infame M2Eclipse issue. 

Not a big deal, just add this `plugin` to your pom.xml file:

```
<plugin>
    <groupId>org.eclipse.m2e</groupId>
    <artifactId>lifecycle-mapping</artifactId>
    <version>1.0.0</version>
    <configuration>
    <lifecycleMappingMetadata>
        <pluginExecutions>
        <pluginExecution>
            <pluginExecutionFilter>
            <groupId>io.fabric8</groupId>
            <artifactId>vertx-maven-plugin</artifactId>
            <versionRange>[1.0.4,)</versionRange>
            <goals>
                <goal>initialize</goal>
            </goals>
            </pluginExecutionFilter>
            <action>
            <ignore />
            </action>
        </pluginExecution>
        </pluginExecutions>
    </lifecycleMappingMetadata>
    </configuration>
</plugin>
```

It just says to Eclipse, "ignore me...". It does not change the behavior of the plugin. 

@kameshsampath - we should document this.

**Comment by nimo23** [comment]
so my pom.xml gets bigger;/..

but thanks!

**Comment by rdcoe** [comment]
This doesn't work for me.  Eclipse still reports:
Plugin execution not covered by lifecycle configuration: io.fabric8:vertx-maven-plugin:1.0.7:initialize (execution: vmp, phase:  initialize)

I've run Maven update and ran mvn clean install

**Comment by rdcoe** [comment]
K, the solution is to wrap it in <pluginManagement><plugins>...</plugins></pluginManagement> inside <build>...</build>
