### ISSUE TITLE
appId not used in vertx:run

### ISSUE THREAD

**Issue by nimo23** [fabric8io/vertx-maven-plugin#121]
I use `<appId>my-app</appId>`. However, it does only work for vertx:start and not for vertx:run. vertx:run does generate a uuid instead of taking the appId "my-app".

**Comment by cescoffier** [comment]
yes, it's the expected behavior.

`vertx:run` launches they application in "redeploy" mode (if `redeploy` is set to `true`) or in frontend (so no `vertx.id` in this case). 

The application id is only used as an admin tool to list the running vert.x application.

**Comment by nimo23** [comment]
Okay, "vertx:run" starts in "foreground-mode", so no need for custom appId.
