### ISSUE TITLE
runArgs or jvmArgs 

### ISSUE THREAD

**Issue by nimo23** [fabric8io/vertx-maven-plugin#122]
I want to put 

`-Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory`

within my vertx-maven-plugin configuration. However, it does not work. Should I use runArgs instead of jvmArgs? 

```
..
<configuration>
<jvmArgs>-Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory</jvmArgs>
</configuration>
..
```

**Comment by kameshsampath** [comment]
@nimo23, your config is not right, please refer here --> https://github.com/tsegismont/vertx-musicstore/blob/master/pom.xml#L140-L145 for the right way. you need to have <jvmArgs>and then jvmArg which should have your jvm arguments
