### ISSUE TITLE
Ordering of resource files with filtering

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/vertx-maven-plugin#129]
When vert.x applications are built with maven resource filtering enabled, the `vert.x` run need to use the resources from the target/classes  rather than from src/main/resources, the filtered resource is copied to target/classes

**Comment by cescoffier** [comment]
@kameshsampath work in progress.

**Comment by kameshsampath** [comment]
thanks @cescoffier - am on PTO , will look in to the includes stuff once back from PTO

**Comment by cescoffier** [comment]
@kameshsampath the includes stuff looks not useful at that point. Let me see if it's useful.

**Comment by cescoffier** [comment]
Just fixed it.
