### ISSUE TITLE
When using Maven 3.5.0, input prompts are not displayed properly.

### ISSUE THREAD

**Issue by InfoSec812** [fabric8io/vertx-maven-plugin#131]
The plugin will still pause waiting on input, but the prompts are not printed to the screen so it appears that the application has frozen.

**Comment by kameshsampath** [comment]
@InfoSec812  - can you please provide steps and screenshots( if possible)

**Comment by InfoSec812** [comment]
Kamesh,

    Just run the setup goal without any properties defined, and that is all
that it takes to reproduce for myself and several others we had in our
workshop at QCon.

[image: Inline image 1]

[image: Inline image 2]

[image: Inline image 3]



Deven

**Comment by InfoSec812** [comment]
![image](https://user-images.githubusercontent.com/99691/27752564-a35713b0-5daf-11e7-8234-129d5f670e0c.png)

**Comment by InfoSec812** [comment]
![image](https://user-images.githubusercontent.com/99691/27752573-ad17983e-5daf-11e7-9dd2-59f6d0170487.png)

**Comment by InfoSec812** [comment]
![image](https://user-images.githubusercontent.com/99691/27752580-b761aaaa-5daf-11e7-9509-5b881eff31fc.png)

**Comment by cescoffier** [comment]
I'm going to have a look to this issue.

**Comment by cescoffier** [comment]
@InfoSec812 @kameshsampath Issue reproduced on my machine.

**Comment by cescoffier** [comment]
The `Prompter` needs to be replaced.

**Comment by InfoSec812** [comment]
Woot!

Deven
