### ISSUE TITLE
Merge resource files when packaging

### ISSUE THREAD

**Issue by MarWestermann** [fabric8io/vertx-maven-plugin#137]
I have a vertx camel application which uses camel-cxf. It works fine when running the application via mvn vertx:run but if I use the vertx-maven-plugin:package to create a fat jar, I get cxf errors.

This is because some of the cxf dependencies all have a META-INF/cxf/bus-extensions.txt file which would need to be merged to the fat jar. But the fat jar only contains the bus-extensions.txt from the "last" dependency.

When I manually create a merged version in /src/main/resources/META-INF/cxf everything is working again.

There should be an option / configuration to decide if resource files needs to get merged

**Comment by cescoffier** [comment]
I definitely agree. Right now, only "SPI" (/META-INF/services) are merged, but we should add an option for this.

The good news is: everything has been done to be able to do it.

**Comment by cescoffier** [comment]
Issues copied to https://github.com/reactiverse/vertx-maven-plugin/issues/12.

**Comment by cescoffier** [comment]
The plugin now has an `archive` attribute that allows configuring which file need to be combined.
Fixed by https://github.com/reactiverse/vertx-maven-plugin/issues/12
