### ISSUE TITLE
Using custom launcher fails to package properly

### ISSUE THREAD

**Issue by InfoSec812** [fabric8io/vertx-maven-plugin#142]
When using a custom launcher via the `vertx.launcher` property, if you use `vertx:package` and try to run the resulting fat-jar it will fail with:

```
Usage: java -jar target/<package>-<version>.jar [COMMAND] [OPTIONS] [arg...]

Commands:
    bare      Creates a bare instance of vert.x.
    list      List vert.x applications
    run       Runs a verticle called <main-verticle> in its own instance of
              vert.x.
    start     Start a vert.x application in background
    stop      Stop a vert.x application
    version   Displays the version.

Run 'java -jar target/<package>-<version>.jar COMMAND --help' for more
information on a command.
```

Expected results: Running the fat-jar will default to the `run` command

Version: 1.0.13

**Comment by InfoSec812** [comment]
I tried to work around this by overriding the `getDefaultCommand` or `getCommandFromManifest`. Neither of these options worked. In the end, I DID find a workaround.. I overrode the `main` method as follows:

```
    public static void main(String[] args) {
        new MetricsLauncher().dispatch(new String[]{"run", MAIN_VERTICLE});
    }
```

**Comment by cescoffier** [comment]
Hi,

Is your class extending Launcher? In that case, yes, the code you write is
required (but this should be documented). If your class does not extend
Launcher but just have a `main` method, then no...

2018-04-15 18:32 GMT+02:00 Deven Phillips <notifications@github.com>:

**Comment by InfoSec812** [comment]
Yes, I am extending Launcher so that I can configure Hawkular metrics via Kubernetes configmaps

**Comment by cescoffier** [comment]
Fixed in https://github.com/reactiverse/vertx-maven-plugin/issues/15.
