### ISSUE TITLE
Java 9 Debug In Docker Container

### ISSUE THREAD

**Issue by stephenstubbs** [fabric8io/vertx-maven-plugin#145]
I have been using the debug option in java 8 with no issues. After upgrading to java 9 it needs the debugging port set to *:5005 in order to debug it from hosts other than localhost but -Ddebug.port=5005 only accepts a number I have tried setting it to to *:5005 which results in an error. I have also tried using the run command and passing in jvm args but I am also unable to get this to work.

**Comment by cescoffier** [comment]
can you provide a reproducer?

**Comment by stephenstubbs** [comment]
Here is a test project [link](https://github.com/sstubbs/vertx-maven-plugin-testproject)

I ran `./steps.sh setup` to setup the project and have just added the timer with the logger which fires every 5 seconds to the verticle to test.

The the three options I have tried are:
`./steps run_with_jvm_args`
`./steps debug_with_jvm_args`
`./steps debug_with_port`

**Comment by stephenstubbs** [comment]
And here is a link to the issue https://stackoverflow.com/questions/46662125/remote-debugging-java-9-in-a-docker-container-from-intellij-idea

I have updated the test project to use the jvmArguments in the issue. I had tried them before but I have just added them here for consistency.

**Comment by stephenstubbs** [comment]
If there is anything else I can do to help please let me know. It would be great to be able to upgrade my project to java 9.

**Comment by cescoffier** [comment]
The fix is quite straightforward I believe. We just need to adapt the `debug.port` configuration to be a string. Fancy a PR?

BTW, the project has been migrated to https://github.com/reactiverse/vertx-maven-plugin, so you should switch to this version instead.

**Comment by stephenstubbs** [comment]
Yes I have been looking through it and like you say all that needs to be done is change it to a string. Sure I can do a pull request. Is there a specific branch you want me to use for it?

**Comment by stephenstubbs** [comment]
Nevermind I see some branches just with issue numbers. I will do a pull request and continue further messages on the new repo.

**Comment by cescoffier** [comment]
Closed by https://github.com/reactiverse/vertx-maven-plugin/pull/33.
