### ISSUE TITLE
Support for xtend

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/vertx-maven-plugin#27]
when xtend is added to the project the application should be able to detect the changes to xtend classes generation and do the incremental build. Currently the application does the rebuild of the src/main/java

**Comment by cescoffier** [comment]
I believe that lots of plugin would need special support if we go this way. We need to find a better "generic" way to handle custom plugin

**Comment by cescoffier** [comment]
(working on it)

**Comment by kameshsampath** [comment]
thanks @cescoffier , closing this via #28
