### ISSUE TITLE
setup goal to add the plugin to pom.xml

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/vertx-maven-plugin#29]
like fabric8:setup can do to add itself to a pom.xml file.

**Comment by kameshsampath** [comment]
@davsclaus - I would prefer this to be added to fabric-forge add-on and am talking with @cescoffier to add the same  vertx-forge add-on. As those would better places to do it . 

Please let me know if you have other thoughts.

**Comment by cescoffier** [comment]
Both ways are fine, `vertx:setup` would avoid depending on forge for people not using forge. It also set the current plugin version (while the forge addon can be outdated a bit).

**Comment by davsclaus** [comment]
Yes we need a simple way from just maven as well so people can quickly get started with vert.x and also easily add the v-m-p plugin.

Just imagine you can show any of the existing forge examples where people struggle with the shade plugin, and then they just run

    mvn io.fabric8.vertx:vertx-maven-plugin:1.0.0:setup

And vupti the plugin is automatic added and it generates a fat jar so running vert.x is easy.

**Comment by cescoffier** [comment]
+1,

I was wondering why not calling it `install`, and then wake up.... Man, getting old.

Will work on it.

**Comment by davsclaus** [comment]
Its called setup in some of the other plugins, and I think install smell like you install an app on an app server (though we favor using deploy/undeploy for those kind of tasks).

**Comment by kameshsampath** [comment]
@davsclaus , this is in via #31. please validate

**Comment by kameshsampath** [comment]
i hope things are working as expected. closing this for now
