### ISSUE TITLE
Add an attach parameter

### ISSUE THREAD

**Issue by cescoffier** [fabric8io/vertx-maven-plugin#70]
Control whether or not the generated archive need to be installed and deployed. `true` by default.

This need to be handle in the package mojo.

**Comment by kameshsampath** [comment]
can you please give an example and add bit detail to this?

**Comment by cescoffier** [comment]
Right now, we attach the create packaged automatically (even when using a classifier I believe). We should still keep this behavior, but allow not attaching the artifact to the project when explicitly set:

A project with:
```
<classifier>vertx</classifier>
<attach>false</attach>
```

would produce:

1. a _bare_ jar file 
2. a fat jar using the `-vertx` classifier

When `attach` is set to false, this second artifact should not be attached to the project. (so not installed in the local maven repo when using `mvn install`, and not deployed with `mvn deploy`).


Now the questions / behaviors are:

1. What does it mean if `classifier` is not set (main artifact) and `attach` is set to `false`
2. `classifier` is set, `attach` not set - the secondary artifact (`-classifier`) should be attached to the project
3. `classifier` is set, `attach` set `true` - the secondary artifact (`-classifier`) should be attached to the project
3. `classifier` is set, `attach` set `false` - the secondary artifact (`-classifier`) should **NOT** be 
attached to the project
4. `classifier` is not set, `attach` set `true` - the primary artifact should be attached to the project
