### ISSUE TITLE
Add an option to exclude dependencies from the packaging

### ISSUE THREAD

**Issue by cescoffier** [fabric8io/vertx-maven-plugin#71]
The package mojo should have an options to filter out some dependencies. Here some thoughts about how it can look like:

```
<excludes>
  <exclude>org.acme:foo</exclude> <- exclude all the dependencies using its groupId:artifactId (regardless the classifier)
  <exclude>org.acme:foo:fat</exclude> <- exlude the dependency using its groupId:artifactId:classifier
  <exclude>org.acme</exclude> <- exclude all dependencies with the matching groupId
```

I'm not sure we need to be complete in the sense that if the fat jar packaging is complex too complex, it should use a specific maven plugin (shader)

**Comment by kameshsampath** [comment]
@cescoffier - are you still looking at adding this, got some bandwidth over next week shall try to push this thing in

**Comment by cescoffier** [comment]
please go ahead @kameshsampath - my bandwidth is rather thin at the moment

**Comment by cescoffier** [comment]
The plugin now has an `archive` attribute that can configure dependency sets. Each set can include/exclude dependencies. 

Fixed by: https://github.com/reactiverse/vertx-maven-plugin/issues/2
