### ISSUE TITLE
Allow passing parameters to the run goals

### ISSUE THREAD

**Issue by cescoffier** [fabric8io/vertx-maven-plugin#82]

**Comment by kameshsampath** [comment]
any example that we could add to this ticket for better understanding - typically like what you pass/configure on plugin etc.,

**Comment by cescoffier** [comment]
Like:


```
vertx run MainVerticle -cluster -instances 2
```

**Comment by kameshsampath** [comment]
so typically `vert.x` specific arguments right ? if the user wishes to pass his custom arguments like `vertx run MainVerticle myProp1 myProp2` ? I hope we are not looking for that here, if so then there are chances that vert.x might parse those arguments and might result in unsuccessful run

**Comment by kameshsampath** [comment]
WIP

**Comment by cescoffier** [comment]
Yes @kameshsampath. These parameters should be passed to the `Launcher` class.

**Comment by kameshsampath** [comment]
closing via #94 #93
